# Site settings
title: Techshoot
email: Rh354@hackermail.com
description: "Just an Ordinary Blog!"
baseurl: /blog
url: "http://techshoot.org"

twitter_username: Rh354
github_username:  Rh354
facebook_username: CupuLegendaris
disqus: indolini

# Build settings
markdown: kramdown
highlighter: pygments
permalink:  /:categories/:title
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

sass:
compressed: true